### ISSUE TITLE
Power On TV Not Working

### ISSUE THREAD

**Issue by Veldkornet** [FricoRico/Homey.SonyBraviaAndroidTV#10]
While I can seem to turn the tv off with Homey, I can’t seem to turn it on... I do have “Remote Start” enabled on the tv... I’m also able to start it with the Sony TV SideView app on iPhone, so not sure what’s happening. 

I have a Sony KD-55X8507C.

**Comment by FricoRico** [comment]
Do you have Wake-on-Lan enabled in the Homey settings? Are you using version 1.0.2 of the app?

**Comment by Veldkornet** [comment]
Yes I have Wake On LAN enabled, and I’ve filled in the MAC and IP etc. 

I have version 1.0.1... I’ve forced it onto 1.0.2 now so I’ll chrck again on that version.

**Comment by Veldkornet** [comment]
Nope, still does not work on 1.0.2. 
Although I had a flow that turned on some backlights when the tv turned on, and this is now instant (since it thinks it turned on the TV) so that now works well. If only the tv actually came on as well ;)

I don’t think it uses standard WOL though since I can’t wake it up with a standard WOL request from my phone either, so the Sony App is doing something else... but it works there what ever it is...

**Comment by FricoRico** [comment]
Could you try to use it without Wake-on-Lan? The library used seems flakey

**Comment by Veldkornet** [comment]
Yes! Turning off the WOL in the settings makes it work! :)

**Comment by FricoRico** [comment]
Sadly I was unable to solve the WOL issues. It turns out BRAVIA televisions struggle with WOL packages at the moment, and there should be no need to use this method anyway. So I removed the option to avoid confusion and slimming down the package furtrher.

**Comment by MrBlue90** [comment]
Actually I got the same issue.
Waking up with this app works perfect: https://apps.athom.com/app/it.diederik.wol
Though it would be nice if the functionality could be copied to this app to save RAM.
Any chance the code could be copied?

Thanks,
Rick

**Comment by UXabre** [comment]
I'd also like to re-instate the Wake-On-LAN option for this plugin. My KDL-55 only seems to be able to power on using WOL (the IRCC message for poweron seems to arrive but nothing really happens).

BTW love the work you've done!
