### ISSUE TITLE
Netflix/EPG triggers don't work

### ISSUE THREAD

**Issue by giggo** [FricoRico/Homey.SonyBraviaAndroidTV#15]
Hi,
The app works very well to send commands to the TV but I don't get any events/triggers back to Homey. I tried Netflix and EPG to trigger Homey flows but this does not work. Any idea?
Ciao,
Gagga

**Comment by FricoRico** [comment]
At the moment Sony does not support this sort of feedback calls through their network API. That is why these events are never fired back when using the TV remote. The triggers are only there for when you use Homey to open Netflix and open the EPG.

I had an Android TV app in the making that would watch the current apps in the foreground to fix these problems. But at the moment this development is on hold.

**Comment by giggo** [comment]
Thanks for the explanation. It would be great if checking the foreground app could be added.

**Comment by FricoRico** [comment]
I will look into making some time for finishing the Android app and releasing it for feedback from the TV

**Comment by whothepope** [comment]
Fwiw, I am also very interested in a companion app to smoothen the experience. My biggest problem is the delay from action to Homey actually noticing (ie. power on, volume change). Still, great work with the app!
