### ISSUE TITLE
Icons do not show in Android/iOS application

### ISSUE THREAD

**Issue by FricoRico** [FricoRico/Homey.SonyBraviaAndroidTV#2]
Some icons do not load in Android and iOS Homey app. This is by now a know issue.

See [this related issue](https://github.com/athombv/homey-vectors-public/issues/51) for more information.

**Comment by WillooWisp** [comment]
I experience this as well, for icons added to custom capabilities. Instead a spinner is shown.

**Comment by FricoRico** [comment]
Issue seems to be resolved automatically on all platforms. Closing the issue.
