### ISSUE TITLE
Homey SDK3

### ISSUE THREAD

**Issue by oh2th** [FricoRico/Homey.SonyBraviaAndroidTV#21]
Hello Ricardo,
You might already know, that Homey SDK2 has been deprecated and apps for Homey need to be updated for SDK3. Athom plans to drop SDK2 now in January.

Do you mind if I took over the update to SDK3. Would you be willing to transfer the app to me from https://tools.developer.homey.app/apps ? And I could start working on the migration.

I'll then just fork the source here in Github and continue from there.

**Comment by oh2th** [comment]
I have a working copy ready https://github.com/oh2th/Homey.SonyBraviaAndroidTV/tree/SDK3
And testing it now.

**Comment by makko77** [comment]
Hi, are there any updates?

**Comment by FricoRico** [comment]
A newer version with SDK3 has now been released
