### ISSUE TITLE
Huge Text Boxes During Pairing

### ISSUE THREAD

**Issue by Veldkornet** [FricoRico/Homey.SonyBraviaAndroidTV#6]
During pairing, if you manually enter the IP/MAC/Key; there is a huge black box that pops up until you enter text. After you enter some text it returns to normal. 

![f275a695-bdde-4eda-805b-1ba26784f7e9](https://user-images.githubusercontent.com/10297361/53266738-f8218a80-36e1-11e9-802f-fb81aac9cbb8.png)

**Comment by FricoRico** [comment]
Thanks for leaving your bugreport. I'm unable to reproduce the issue on my Android phone or on the developer pairing test environment.

I will test on a physical iPhone next monday and report back my findings. What version of Homey are you using?

**Comment by Veldkornet** [comment]
Homey: 2.0.2
Homey iOS: 2.0.8

**Comment by FricoRico** [comment]
I was able to replicate the issue. It's not the input itself that turns black, but the page scrolls up too far showing the black background. If you scroll before doing some input you can see what I mean.

I'm unsure if I can fix it on my side, but I will make attempts to do so.

**Comment by FricoRico** [comment]
I managed to reduce the problem a bit, but I am unable to get rid of the issue completely. A black bar is still shown but not on top of the buttons any longer.

This is an issue with the iOS Homey app, as it also occurs on Homeys `login_credentials` screens. I reported the i[ssue at the Homey repository](https://github.com/athombv/homey-apps-sdk-issues/issues/70).

**Comment by FricoRico** [comment]
Issue should be solved in Homey 2.1.0 app, see linked homey issue.
