### ISSUE TITLE
Error messages when pressing device buttons

### ISSUE THREAD

**Issue by Whireking** [FricoRico/Homey.SonyBraviaAndroidTV#8]
When pressing the channel up / down and volume up/down/muted buttons I get two different error messages. For example if I press the volume down button it changes the volume after a few seconds, but the below two error messages also show up. The network request failed shows up first, and after a few seconds the timeout shows up (earlier than 30 seconds). This happens for all of the 5 buttons.
I am using Homey 2.0.2 and have the Sony KD-49X8305C from 2015.

![whatsapp image 2019-02-23 at 13 45 54 2](https://user-images.githubusercontent.com/47777957/53286782-e5f02c80-3773-11e9-9301-d5e385dbf5af.jpeg)
![whatsapp image 2019-02-23 at 13 45 54 5](https://user-images.githubusercontent.com/47777957/53286783-e688c300-3773-11e9-8485-50e5c0f02d48.jpeg)

**Comment by FricoRico** [comment]
I noticed this too, buttons work sporadically. But spamming them gives this error. No errors show up in de application logs, and the error showing is not my error.

It might be a weird asynchronous error so I will investigate further looking for bugs that can cause this.

**Comment by FricoRico** [comment]
Issue should be resolved with app version **1.0.2**. Can you please confirm?

**Comment by Whireking** [comment]
With the app version 1.0.2. it is working correctly. Thank you!
